# Generated by Django 4.1.3 on 2023-10-27 23:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('harga', models.IntegerField()),
                ('gambar', models.ImageField(upload_to='barang/images/')),
                ('stok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('telpon', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='min 8 digit', regex='^\\+?1?\\d{9,15}$')])),
                ('alamat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.barang')),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='toko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.toko'),
        ),
    ]
